### ISSUE TITLE
Not all items have a Score (TurtleWoW)

### ISSUE THREAD

**Issue by JustVityok** [shagu/ShaguScore#2]
The issue is in title. Can we get GS calculated for TWoW's custom items?

**Comment by shagu** [comment]
Nope, the database is not open source. Sorry

**Comment by Drexl** [comment]
Just adding my 2c that I'd like to see this as well.

**Comment by shagu** [comment]
update: as of https://github.com/shagu/ShaguScore/commit/586dc15202200aeba7047e6b4601f69b696a0459, all turtle-wow custom items now show the itemLevel
