### ISSUE TITLE
Simple item level display (turtle wow)

### ISSUE THREAD

**Issue by offerduo** [shagu/ShaguScore#3]
Is it possbile to have an option to display just item level instead of score for each item and the average item level of a character?
Some raid leader pushes a lot on average item level.

**Comment by HerrTiSo** [comment]
> Is it possbile to have an option to display just item level instead of score for each item and the average item level of a character? Some raid leader pushes a lot on average item level.

iLevel = ShaguScore; but in the end, all of this is of a purely highly theoretical nature, especially in Vanilla.
